routes/web.php
<?php

use App\Http\Controllers\TourController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('tours', [TourController::class, 'index'])->name('tours');
Route::get('tours/{tour:slug}', [TourController::class, 'show'])->name('tour');

/** CATCH-ALL ROUTE for Backpack/PageManager **/
Route::get('{page}/{subs?}', ['uses' => '\App\Http\Controllers\PageController@index'])
    ->where(['page' => '^(((?=(?!admin))(?=(?!\/)).))*$', 'subs' => '.*']);

app/Models/Tour.php
<?php

namespace App\Models;

use App\Enums\SeasonEnum;
use App\Traits\CanTableName;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Tour extends Model
{
    use CrudTrait;
    use CanTableName;
    use Sluggable;

    private const DAYS_IN_WEEK = 7;

    public const FIELD_TITLE = 'title';
    public const FIELD_DESCRIPTION = 'description';
    public const FIELD_SLUG = 'slug';
    public const FIELD_COUNTRY = 'country_id';
    public const FIELD_REGION = 'region_id';
    public const FIELD_CITY = 'city_id';
    public const FIELD_TRIP_THEME = 'trip_theme_id';
    public const FIELD_TRIP_THEME_TYPE = 'trip_theme_type_id';
    public const FIELD_TRIP_START = 'start_trip_date';
    public const FIELD_TRIP_END = 'end_trip_date';
    public const FIELD_USER_PRICE = 'user_price';
    public const FIELD_IS_PUBLISH = 'is_publish';


    protected $casts = [
        self::FIELD_TRIP_START => 'datetime',
        self::FIELD_TRIP_END   => 'datetime',
    ];

    protected $fillable = [
        self::FIELD_TITLE,
        self::FIELD_DESCRIPTION,
        self::FIELD_SLUG,
        self::FIELD_COUNTRY,
        self::FIELD_REGION,
        self::FIELD_CITY,
        self::FIELD_TRIP_THEME,
        self::FIELD_TRIP_THEME_TYPE,
        self::FIELD_TRIP_START,
        self::FIELD_TRIP_END,
        self::FIELD_USER_PRICE,
        self::FIELD_IS_PUBLISH,
    ];

    protected static function boot()
    {
        parent::boot();
        static::saving(function ($model) {
            if ($model->isDirty(self::FIELD_TRIP_START) || $model->isDirty(self::FIELD_TRIP_END)) {
                $model->week_of_year = $model->start_trip_date->weekOfYear;
                $model->month_of_year = $model->start_trip_date->month;
                $model->season_of_year = SeasonEnum::getSeason($model->start_trip_date->month);
                $model->duration = $model->end_trip_date->diffInDays($model->start_trip_date);
                $model->duration_in_week = ceil($model->duration / self::DAYS_IN_WEEK);
            }
        });
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title',
            ],
        ];
    }

    public function country(): BelongsTo
    {
        return $this->belongsTo(Country::class);
    }

    public function region(): BelongsTo
    {
        return $this->belongsTo(Region::class);
    }

    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function tripTheme(): BelongsTo
    {
        return $this->belongsTo(TripTheme::class);
    }

    public function tripThemeType(): BelongsTo
    {
        return $this->belongsTo(TripThemeType::class);
    }

    public function ageCategories(): BelongsToMany
    {
        return $this->belongsToMany(AgeCategory::class);
    }

    public function products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class);
    }

    public function getPriceAttribute(): string
    {
        return 'CHF ' . $this->attributes['user_price'];
    }
}

resources/views/pages/contact.blade.php
@extends('layouts.main')

@section('content')

    <section class="page-title centred" style="background-image: url({{asset('/images/background/page-title-5.jpg')}});">
        <div class="auto-container">
            <div class="content-box">
                <h1>{{ __('main.contact') }}</h1>
            </div>
        </div>
    </section>

    <section class="contact-info-section bg-color-1">
        <div class="anim-icon">
            <div class="icon anim-icon-1" style="background-image: url({{asset('/images/shape/shape-3.png')}});"></div>
            <div class="icon anim-icon-2" style="background-image: url({{asset('/images/shape/shape-3.png')}});"></div>
        </div>
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-lg-4 col-md-6 col-sm-12 info-column">
                    <div class="single-info-box wow fadeInUp animated animated" data-wow-delay="00ms" data-wow-duration="1500ms">
                        <div class="inner-box">
                            <div class="icon-box"><i class="icon-Location"></i></div>
                            <h3>{{ __('main.address') }}</h3>
                            <p>EWA Solutions GmbH
                                Unter Altstadt 10
                                6300 Zug</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 info-column">
                    <div class="single-info-box wow fadeInUp animated animated" data-wow-delay="300ms" data-wow-duration="1500ms">
                        <div class="inner-box">
                            <div class="icon-box"><i class="icon-Phone"></i></div>
                            <h3>{{ __('main.phone') }}</h3>
                            <p><a href="tel:0041765220158">0041 76 522 01 58</a></p>
                            <p>&nbsp;</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 info-column">
                    <div class="single-info-box wow fadeInUp animated animated" data-wow-delay="600ms" data-wow-duration="1500ms">
                        <div class="inner-box">
                            <div class="icon-box"><i class="icon-Envelope"></i></div>
                            <h3>{{ __('main.email') }}</h3>
                            <p><a href="mailto:info@example.com">info@ewasolutions.ch</a></p>
                            <p>&nbsp;</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="contact-section">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-12 col-sm-12 content-column">
                    <div class="content_block_5">
                        <div class="content-box">
                            <div class="sec-title">
                                <h2>Uns finden Sie auch offline</h2>
                            </div>
                            <div class="text">
                                <p>{{ Str::upper(__('main.contact')) }}</p>
                                <p>
                                    <a class="text-secondary" href="mailto:info@ewasolutions.ch">info@ewasolutions.ch</a>
                                    <br>
                                    <a class="text-secondary" href="tel:0765220058">076 522 01 58</a>
                                </p>
                                <p>Unter Altstadt 10, 6300 Zug</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 col-md-12 col-sm-12 form-column">
                    <div class="form-inner">
                        <form method="post" action="sendemail.php" id="contact-form" class="default-form">
                            <div class="row clearfix">
                                <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                    <input type="text" name="username" placeholder="{{ __('main.name') }}" required="">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12 form-group">
                                    <input type="email" name="email" placeholder="{{ __('main.email') }}" required="">
                                </div>
                                <div class="col-lg-6 col-md-12 col-sm-12 form-group">
                                    <input type="text" name="phone" required="" placeholder="{{ __('main.phone') }}">
                                </div>
                                <div class="col-lg-6 col-md-12 col-sm-12 form-group">
                                    <input type="text" name="subject" required="" placeholder="{{ __('main.subject') }}">
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                                    <textarea name="message" placeholder="{{ __('main.message') }}"></textarea>
                                </div>
                                <div class="col-lg-12 col-md-12 col-sm-12 form-group message-btn">
                                    <button class="theme-btn" type="submit" name="submit-form">{{ __('main.send') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/pages/destinations.blade.php
@extends('layouts.main')

@section('content')

    <section class="page-title centred" style="background-image: url({{ asset('/images/background/page-title.jpg')}});">
        <div class="auto-container">
            <div class="content-box">
                <h1>{{ __('main.destinations') }}</h1>
            </div>
        </div>
    </section>

    <section class="place-section sec-pad-2">
        <div class="anim-icon">
            <div class="icon anim-icon-1" style="background-image: url({{ asset('/images/icons/anim-icon-1.png')}});"></div>
            <div class="icon anim-icon-2" style="background-image: url({{ asset('assets/images/shape/shape-3.png')}});"></div>
            <div class="icon anim-icon-3" style="background-image: url({{ asset('assets/images/shape/shape-3.png')}});"></div>
        </div>
        <div class="auto-container">
            <div class="row clearfix">
                @foreach($countries as $country)
                    <div class="col-lg-4 col-md-6 col-sm-12 place-block">
                        <div class="place-block-one">
                            <div class="inner-box">
                                <figure class="image-box"><img src="{{ asset('/images/resource/place-1.jpg')}}" alt=""></figure>
                                <div class="text">
                                    <h3>
                                        <a href="{{ route('tours', ['country' => $country->code]) }}">
                                            {{ __('country.'.$country->name) }}
                                        </a>
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>

@endsection

resources/views/pages/tour_details.blade.php
@extends('layouts.main')

@section('content')

    <section class="page-title style-three" style="background-image: url({{asset('/images/background/page-title-3.jpg')}});">
        <div class="auto-container">
            <div class="inner-box">
                <h2>MIKE WIEGELE: VON KÄRNTEN NACH KANADA</h2>
                <h3>CHF 1700.00<span> / Per person</span></h3>
            </div>
        </div>
    </section>

    <section class="tour-details">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 content-side">
                    <div class="tour-details-content">
                        <div class="inner-box">
                            <div class="text">
                                <h2>Overview</h2>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                                <ul class="info-list clearfix">
                                    <li><i class="far fa-clock"></i>5 Days</li>
                                    <li><i class="far fa-user"></i>Age 15+</li>
                                    <li><i class="far fa-map"></i>G87P, Birmingham</li>
                                </ul>
                            </div>
                        </div>
                        <div class="overview-inner">
                            <ul class="overview-list clearfix">
                                <li><span>Destination:</span>Kanada</li>
                                <li><span>Departure:</span>Yes Requard</li>
                                <li><span>Departure Time:</span>New York City</li>
                                <li><span>Return Time:</span>English & Spanish</li>
                                <li class="clearfix"><span>Included:</span>
                                    <ul class="included-list clearfix">
                                        <li>Air fares</li>
                                        <li>4 Nights Hotel Accomodation</li>
                                        <li>Entrance Fees</li>
                                        <li>Tour Guide</li>
                                    </ul>
                                </li>
                                <li class="clearfix"><span>Excluded:</span>
                                    <ul class="excluded-list clearfix">
                                        <li>Air fares</li>
                                        <li>Air fares</li>
                                        <li>Air fares</li>
                                        <li>Air fares</li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="tour-plan">
                            <div class="text">
                                <h2>Tour Plan</h2>
                                <p>Aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                            </div>
                            <div class="content-box">
                                <div class="single-box">
                                    <span>01</span>
                                    <h4>8:00 am to 10:00 am</h4>
                                    <h3>Day 1: Arrive South Africa Forest</h3>
                                    <p>Aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                    <ul class="list clearfix">
                                        <li>Air fares</li>
                                        <li>4 Nights Hotel Accomodation</li>
                                        <li>Entrance Fees</li>
                                    </ul>
                                </div>
                                <div class="single-box">
                                    <span>02</span>
                                    <h4>8:00 am to 10:00 am</h4>
                                    <h3>Day 2: Arrive South Africa Forest</h3>
                                    <p>Aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                    <ul class="list clearfix">
                                        <li>Air fares</li>
                                        <li>4 Nights Hotel Accomodation</li>
                                        <li>Entrance Fees</li>
                                    </ul>
                                </div>
                                <div class="single-box">
                                    <span>03</span>
                                    <h4>8:00 am to 10:00 am</h4>
                                    <h3>Day 3: Arrive South Africa Forest</h3>
                                    <p>Aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                    <ul class="list clearfix">
                                        <li>Air fares</li>
                                        <li>4 Nights Hotel Accomodation</li>
                                        <li>Entrance Fees</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="location-map">
                            <div class="text">
                                <h2>View On Map</h2>
                                <p>Enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat duis aute irure dolor.</p>
                            </div>
                            <div class="map-inner">
                                <div
                                    class="google-map"
                                    id="contact-google-map"
                                    data-map-lat="40.712776"
                                    data-map-lng="-74.005974"
                                    data-icon-path="{{asset('/images/icons/map-marker.png')}}"
                                    data-map-title="Brooklyn, New York, United Kingdom"
                                    data-map-zoom="12"
                                    data-markers='{
                                            "marker-1": [40.712776, -74.005974, "<h4>Branch Office</h4><p>77/99 New York</p>","{{asset('/images/icons/map-marker.png')}}"]
                                        }'>

                                </div>
                            </div>
                        </div>
                        <div class="photo-gallery">
                            <div class="text">
                                <h2>Photo Gallery</h2>
                                <p>Enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                            </div>
                            <div class="image-box clearfix">
                                <figure class="image">
                                    <img src="{{asset('/images/resource/destination-44.jpg')}}" alt="">
                                    <a href="{{asset('/images/resource/destination-4.jpg')}}" class="view-btn lightbox-image" data-fancybox="gallery"><i class="icon-Plus"></i></a>
                                </figure>
                                <figure class="image">
                                    <img src="{{asset('/images/resource/destination-44.jpg')}}" alt="">
                                    <a href="{{asset('/images/resource/destination-4.jpg')}}" class="view-btn lightbox-image" data-fancybox="gallery"><i class="icon-Plus"></i></a>
                                </figure>
                                <figure class="image">
                                    <img src="{{asset('/images/resource/destination-44.jpg')}}" alt="">
                                    <a href="{{asset('/images/resource/destination-4.jpg')}}" class="view-btn lightbox-image" data-fancybox="gallery"><i class="icon-Plus"></i></a>
                                </figure>
                                <figure class="image">
                                    <img src="{{asset('/images/resource/destination-55.jpg')}}" alt="">
                                    <a href="{{asset('/images/resource/destination-555.jpg')}}" class="view-btn lightbox-image" data-fancybox="gallery"><i class="icon-Plus"></i></a>
                                </figure>
                                <figure class="image">
                                    <img src="{{asset('/images/resource/destination-44.jpg')}}" alt="">
                                    <a href="{{asset('/images/resource/destination-4.jpg')}}" class="view-btn lightbox-image" data-fancybox="gallery"><i class="icon-Plus"></i></a>
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 sidebar-side">
                    <div class="default-sidebar tour-sidebar ml-20">
                        <div class="advice-widget">
                            <div class="inner-box" style="background-image: url({{asset('/images/resource/advice-1.jpg')}});">
                                <div class="text">
                                    <h2>Get <br />25% Off <br />On New York Tours</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/pages/tours.blade.php
@extends('layouts.main')

@section('content')
    <section class="page-title style-two centred" style="background-image: url({{asset('/images/background/page-title-2.jpg')}});">
        <div class="auto-container">
            <div class="content-box">
                <h1>{{ __('main.tours') }}</h1>
            </div>
            <div class="form-inner">
                <form action="index.html" method="post" class="booking-form clearfix">
                    <div class="form-group">
                        <input type="text" name="service" placeholder="{{ __('main.filter.where') }}" required=""
                         value="{{ $filter->country ? __('country.' . $filter->country->name)  : '' }}">
                    </div>
                    <div class="form-group input-date">
                        <i class="far fa-angle-down"></i>
                        <input type="text" name="date" placeholder="{{ __('main.filter.when') }}" id="datepicker">
                    </div>
                    <div class="form-group">
                        <div class="select-box">
                            <select class="wide">
                                <option data-display="Travel Type">{{ __('main.travel_type') }}</option>
                                <option value="1">Adventure Tours</option>
                                <option value="2">City Tours</option>
                                <option value="3">Couple Tours</option>
                                <option value="4">Group Tours</option>
                            </select>
                        </div>
                    </div>
                    <div class="message-btn">
                        <button type="submit" class="theme-btn"><i class="far fa-search"></i>{{ __('main.find') }}</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <section class="tours-page-section">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 content-side">
                    <div class="item-shorting clearfix">
                        <div class="left-column pull-left">
                            <h3>{{ __('main.showing') }} {{ $tours->firstItem() }} - {{ $tours->lastItem() }} of {{ $tours->total() }}</h3>
                        </div>
                        <div class="right-column pull-right clearfix">
                            <div class="short-box clearfix">
                                <div class="select-box">
                                    <select class="wide">
                                        <option data-display="Sort by">{{ __('main.sort_by') }}</option>
                                        <option value="1">{{ __('main.sort.name_a_to_z') }}</option>
                                        <option value="2">{{ __('main.sort.name_z_to_a') }}</option>
                                        <option value="3">{{ __('main.sort.price_low_to_high') }}</option>
                                        <option value="3">{{ __('main.sort.price_high_low') }}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="wrapper grid">
                        <div class="tour-grid-content">
                            <div class="row clearfix">
                                @foreach($tours as $tour)
                                    <div class="col-lg-4 col-md-6 col-sm-12 tour-block">
                                        <div class="tour-block-one wow fadeInUp animated animated" data-wow-delay="00ms"
                                             data-wow-duration="1500ms">
                                            <div class="inner-box">

                                                <figure class="image-box">
                                                    <img src="{{ $supplierService->getFirstImage($tour->products()->first()->supplier) }}" alt="">
                                                    <a href="{{ route('tour', $tour->slug) }}"><i class="fas fa-link"></i></a>
                                                </figure>

                                                <div class="lower-content">
                                                    <h3><a href="{{ route('tour', $tour->slug) }}">{{ $tour->title }}</a></h3>
                                                    <h4>{{ $tour->price }}<span> / Per person</span></h4>
                                                    <ul class="info clearfix">
                                                        <li><i class="far fa-clock"></i>{{ $tour->duration }} {{ __('main.days') }}</li>
                                                        <li><i class="far fa-map"></i>{{ $tour->country->name }}, {{ $tour->region->code }}</li>
                                                    </ul>
                                                    {!! $tour->description !!}
                                                    <div class="btn-box">
                                                        <a href="{{ route('tour', $tour->slug) }}">{{ __('main.details') }}</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>

                    @if ($tours->hasPages())
                        <div class="pagination-wrapper">
                            <ul class="pagination clearfix">
                                @if (!$tours->onFirstPage())
                                    <li><a href="{{ $tours->previousPageUrl() }}"><i class="icon-Left-Arrow"></i></a></li>
                                @endif

                                @for($i = 1; $i <= $tours->lastPage(); $i++)
                                    @if ($i === $tours->currentPage())
                                        <li><a href="#" class="current">{{ $i }}</a></li>
                                    @else
                                        <li><a href="{{ $tours->url($i) }}">{{ $i }}</a></li>
                                    @endif
                                @endfor

                                @if ($tours->hasMorePages())
                                    <li><a href="{{ $tours->nextPageUrl() }}"><i class="icon-Right-Arrow"></i></a></li>
                                @endif
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </section>
@endsection